/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CryptoIndexRouteImport } from './routes/crypto/index'
import { Route as CryptoCoinRouteImport } from './routes/crypto/$coin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoIndexRoute = CryptoIndexRouteImport.update({
  id: '/crypto/',
  path: '/crypto/',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoCoinRoute = CryptoCoinRouteImport.update({
  id: '/crypto/$coin',
  path: '/crypto/$coin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crypto/$coin': typeof CryptoCoinRoute
  '/crypto/': typeof CryptoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crypto/$coin': typeof CryptoCoinRoute
  '/crypto': typeof CryptoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crypto/$coin': typeof CryptoCoinRoute
  '/crypto/': typeof CryptoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crypto/$coin' | '/crypto/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crypto/$coin' | '/crypto'
  id: '__root__' | '/' | '/crypto/$coin' | '/crypto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CryptoCoinRoute: typeof CryptoCoinRoute
  CryptoIndexRoute: typeof CryptoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/': {
      id: '/crypto/'
      path: '/crypto'
      fullPath: '/crypto/'
      preLoaderRoute: typeof CryptoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/$coin': {
      id: '/crypto/$coin'
      path: '/crypto/$coin'
      fullPath: '/crypto/$coin'
      preLoaderRoute: typeof CryptoCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CryptoCoinRoute: CryptoCoinRoute,
  CryptoIndexRoute: CryptoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
